// ==UserScript==
// @name         MorphoSource Cart Sortable Table
// @namespace    https://www.morphosource.org/
// @version      0.1
// @description  Make the cart tables sortable (client-side) by clicking column headers.
// @author       Generated by Copilot
// @match        https://www.morphosource.org/dashboard/my/cart*
// @run-at       document-end
// ==/UserScript==

(function() {
  'use strict';

  // Map column index -> sort type
  const SORT_TYPES_BY_INDEX = {
    // 0: checkbox, 1: thumbnail, 2: Id, 3: Title, 4: Object, 5: Taxonomy, 6: Date Added, 7: Approved, 8: Expires, 9: Action
    0: 'none',
    1: 'none',
    2: 'number',
    3: 'text',
    4: 'text',
    5: 'text',
    6: 'date',
    7: 'date',
    8: 'date',
    9: 'none'
  };

  const STYLE = `
    .ms-sortable { cursor: pointer; user-select: none; }
    .ms-sortable:after { content: ' ▴▾'; opacity: 0.3; font-size: 0.9em; padding-left: 4px; }
    th[aria-sort="ascending"]::after { content: ' ▴'; opacity: 0.9; }
    th[aria-sort="descending"]::after { content: ' ▾'; opacity: 0.9; }
  `;

  function injectStyle() {
    if (document.getElementById('ms-cart-sort-style')) return;
    const s = document.createElement('style');
    s.id = 'ms-cart-sort-style';
    s.textContent = STYLE;
    document.head.appendChild(s);
  }

  function normalizeText(s) {
    if (!s) return '';
    try {
      return s.trim().toLowerCase();
    } catch (e) { return s; }
  }

  function cellText(td) {
    if (!td) return '';
    return td.textContent.trim();
  }

  function parseValueByType(val, type) {
    if (type === 'number') {
      const n = parseFloat(String(val).replace(/[^0-9.\-]+/g, ''));
      return isNaN(n) ? Number.NEGATIVE_INFINITY : n;
    }
    if (type === 'date') {
      // Accept YYYY-MM-DD or common localized formats; fallback to Date.parse
      const iso = /^(\d{4})-(\d{2})-(\d{2})/.exec(val);
      if (iso) return Date.parse(iso[0]);
      const ts = Date.parse(val);
      return isNaN(ts) ? Number.NEGATIVE_INFINITY : ts;
    }
    // text
    return normalizeText(String(val).normalize ? String(val).normalize('NFD').replace(/\p{Diacritic}/gu, '') : val);
  }

  function getThIndex(th) {
    let idx = 0;
    let n = th;
    while ((n = n.previousElementSibling)) {
      if (n.tagName === 'TH') idx++;
    }
    return idx;
  }

  function clearAriaSort(ths) {
    ths.forEach(t => t.removeAttribute('aria-sort'));
  }

  function makeSortable(table) {
    if (!table || table.dataset.msSortable === '1') return;
    const thead = table.querySelector('thead');
    const tbody = table.querySelector('tbody');
    if (!thead || !tbody) return;

    const ths = Array.from(thead.querySelectorAll('th'));
    ths.forEach((th, i) => {
      const type = SORT_TYPES_BY_INDEX[i] ?? 'text';
      if (type === 'none') return;

      th.classList.add('ms-sortable');
      th.setAttribute('role', 'button');
      th.setAttribute('tabindex', '0');
      th.dataset.msSortType = type;

      const handler = (ev) => {
        if (ev.type === 'click' || (ev.type === 'keydown' && (ev.key === 'Enter' || ev.key === ' '))) {
          ev.preventDefault();
          const idx = getThIndex(th);
          const sortType = th.dataset.msSortType || 'text';
          const currentDir = th.getAttribute('aria-sort');
          const newDir = currentDir === 'ascending' ? 'descending' : 'ascending';

          // Reset other headers
          clearAriaSort(ths);
          th.setAttribute('aria-sort', newDir);

          // Collect rows and decorate with stable index
          const rows = Array.from(tbody.querySelectorAll('tr'));
          const decorated = rows.map((row, pos) => {
            const td = row.children[idx];
            const val = cellText(td);
            const parsed = parseValueByType(val, sortType);
            return { row, key: parsed, pos };
          });

          decorated.sort((a, b) => {
            const dir = newDir === 'ascending' ? 1 : -1;
            if (a.key < b.key) return -1 * dir;
            if (a.key > b.key) return 1 * dir;
            // stable
            return (a.pos - b.pos);
          });

          // Reinsert rows
          const frag = document.createDocumentFragment();
          decorated.forEach(d => frag.appendChild(d.row));
          tbody.appendChild(frag);
        }
      };

      th.addEventListener('click', handler);
      th.addEventListener('keydown', handler);
    });

    table.dataset.msSortable = '1';
  }

  function enhanceAll() {
    injectStyle();
    const tables = Array.from(document.querySelectorAll('.cart-page table.works-list, #unrestricted_documents table.works-list, #restricted_documents table.works-list'));
    tables.forEach(makeSortable);
  }

  // Initial run
  enhanceAll();

  // Observe for table reloads (e.g., rows per page change)
  const mo = new MutationObserver(() => enhanceAll());
  mo.observe(document.body, { childList: true, subtree: true });

  // Safety re-run once after load
  setTimeout(enhanceAll, 500);
  setTimeout(enhanceAll, 1500);
})();
